apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ingestion-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ingestion
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
