apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: disloman
  labels:
    app: disloman
spec:
  ports:
  - protocol: TCP
    # Gli altri Services/Pods del cluster per comunicare con questo Servizio dovranno quindi fare riferimento al suo DNS NAME: ingestion-service e PORT NUMER:8080
    port: 8080
  selector:
    app: ingestion
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestion-microservice
  namespace: disloman
spec:
  selector:
    matchLabels:
        app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: drugotosto84/ingestion-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kub"
        # Lista delle porte che il dato container espone (solitamente 1) e che sono quindi accoppiate con quelle definite all'interno del suo Dockerfile (non è necesseria definirla)
        # Sulla data porta ci sarà in ascolto una determinata applicazione 
        ports:
        - containerPort: 8080
  replicas: 1
  # Aspetta 10 sencondi prima di considerare ogni Pod pronto
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Il Rolling Update avverrà tirando giù un Pod alla volta
      maxUnavailable: 1
      # Il Rolling Update avverrà senza avere più di 1 extra Pod esistente rispetto a quelli complessivi stabiliti da
      maxSurge: 1

