apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oee-computation-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: oee-computation
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
