# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: mongodns
  namespace: disloman
  labels:
     app: disloman
     name: mongo
spec:
  ports:
  - port: 27017
  # mongo-<num>.kafkadns disloman.svc.cluster.local
  clusterIP: None
  selector:
    app: mongo