# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: disloman
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo