apiVersion: v1
kind: Service
metadata:
  name: zoodns
  namespace: disloman
  labels:
    app: disloman
    name: zookeeper
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper