apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-manager
  namespace: disloman-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: mzagar/kafka-manager-docker:1.3.3.4
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: zookeeper:2181
  